feat: show graphql operation name for graphql requests
infinitered/reactotron pull request #1521
Opened 2024-11-08 15:44 UTC by yurik256

## Please verify the following:
- [ ] `yarn build-and-test:local` passes
- [ ] I have added tests for any new features, if relevant
- [ ] `README.md` (or relevant documentation) has been updated with your changes

## Describe your PR
On the react native project I'm working on, we are extensively using graphql. 
Current implement of timeline plugin, makes it hard to differentiate graphql requests, as they are all shown as `POST /graphql` in the timeline

This PR improves this by adding the following
* show operation name for graphql requests
   * This is implemented by parsing `request.operationName` field, which is automatically added for all graphql requests made by `@apollo/client`
* Ability to filter requests by request data

**Screenshots**

Show operation name
![Screenshot 2024-11-08 at 10 41 40 AM](https://github.com/user-attachments/assets/bc74fd3c-c776-417a-a588-55ed812e9e05)

Ability to search by request data ( in this case, operation name ) 
![Screenshot 2024-11-08 at 10 41 59 AM](https://github.com/user-attachments/assets/e2ea74c1-8e6e-4088-913c-8a6ca6240c6d)

2024-11-14 16:35 UTC, yurik256 commented
The contributing guide, unfortunately, doesn't specify who should be marked as the reviewer. 
@morganick, I see that you reviewed a few recent PRs, would you mind taking a look?

2024-11-29 15:02 UTC, morganick requested changes
Sorry for such a long delay in this. I had a couple of moments this morning and had the tab still open 😅 I haven't had a chance to fully test this out with a GraphQL API & Apollo Client. I'll look at doing that next week.

2024-12-20 13:20 UTC, frankcalise commented
@yurik256 thanks for the contribution! Do you have the time to make the requested changes by Nick? If not let us know and we can try to bring it up to speed.

2024-12-20 15:01 UTC, yurik256 commented
> @yurik256 thanks for the contribution! Do you have the time to make the requested changes by Nick? If not let us know and we can try to bring it up to speed.

@frankcalise thanks for following up! I somehow missed the message from @morganick :( 
The suggested change to use join makes sense. Just pushed the changes.

I tried changing the order so that we show the operation name before the URL, and that makes it visually hard to parse. 
It could be that I'm also just used to the fact that URL should come first 🤷‍♂️  
I would like to propose that we display the operation name after the URL.
@morganick, what do you think?

operation name before:
![image](https://github.com/user-attachments/assets/feff8e8b-b744-4384-9333-07f5e3b5a3d5)

operation name after: 
![384430781-bc74fd3c-c776-417a-a588-55ed812e9e05](https://github.com/user-attachments/assets/dc4f3199-4992-4767-9592-0c1b504ca2fb)

2024-12-20 15:12 UTC, morganick commented
@yurik256 I'm good with putting it after the URL. I'd love to update the design of the timeline to accommodate for things like this. It gets lost a bit either way, but I agree that after is easier on the eyes because of the uniformity of the pattern in `POST /url/goes/here`

2025-01-07 15:10 UTC, morganick approved these changes
LGTM 👍

2025-01-28 17:40 UTC, merged